<#1>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#2>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#3>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#4>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#5>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#6>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
<#7>
<?php
\srag\Plugins\SrAutoMails\Repository::getInstance()->installTables();
?>
