<#1>
<?php
\srag\Plugins\SrAutoMails\Config\Config::updateDB();
\srag\Plugins\SrAutoMails\Rule\Rule::updateDB();
\srag\Plugins\SrAutoMails\Sent\Sent::updateDB();
?>
<#2>
<?php
\srag\Plugins\SrAutoMails\Rule\Rule::updateDB();
?>
